### ISSUE TITLE
Weak

### ISSUE THREAD

**Issue by 0u44** [M1noa/ddos-Tool#1]
Just saying, this DDoS tools is one VERY WEAK one...

**Comment by CPScript** [comment]
hmmmm, actually i change my mind... it might

**Comment by M1noa** [comment]
Its weak cause it runs off your wifi, this is a shitty ass script sooo I have a better script i made but its private

**Comment by CPScript** [comment]
> Its weak cause it runs off your wifi, this is a shitty ass script sooo I have a better script i made but its private

I never said it was good... Please don't talk shit about some of my early projects.

**Comment by CPScript** [comment]
Oh shit... I thought this was someone talking shit about one of my repos... Don't mind my last comment(s)

**Comment by CPScript** [comment]
Also... Don't make a DDoS tool that uses wifi... This will get you and the users in legal trouble... Make it a middleman DDoS tool.

**Comment by M1noa** [comment]
This script isn't made to be used. Its made for fun i made it to run on a vps just to slow down some idiots
